### ISSUE TITLE
请问NativeScript 如何调用原生代码?

### ISSUE THREAD

**Issue by guotingchao** [eeandrew/NSCalculator#2]
``` js
var alert = new UIAlertView(); 
```

比如这个并不成功 需要引入哪些文件呢？我在官网文档找了两天有没有看见资料。
[这个博客上的描述](http://www.cnblogs.com/ihardcoder/p/5306402.html)

如果您知道 麻烦指点下。

**Comment by eeandrew** [comment]
https://github.com/eeandrew/nativescript-fancyalert
